### ISSUE TITLE
Chart gets bigger when it refreshes?

### ISSUE THREAD

**Issue by ScottBeeson** [robdodson/chart-elements#10]
Here is my HTML:

    <chart-pie id="alarmPie" width="120"></chart-pie>

And I'm updating the data via jQuery like so (Terrible, I'm sure)

    $('#alarmPie').attr('values','[' + cServers + ',' + cNetwork + ',' + cApps + ']')

Each time the data updates, the chart gets bigger.  I've watched the numbers and it seems arbitrary... Here are a few examples:

    <canvas id="canvas" width="145" height="181" style="width: 132px; height: 165px;"></canvas>
    <canvas id="canvas" width="159" height="199" style="width: 145px; height: 181px;"></canvas>
    <canvas id="canvas" width="174" height="218" style="width: 159px; height: 199px;"></canvas>
    <canvas id="canvas" width="191" height="239" style="width: 174px; height: 218px;"></canvas>
    <canvas id="canvas" width="210" height="262" style="width: 191px; height: 239px;"></canvas>

**Comment by robdodson** [comment]
Closing as can't repro. Happen to reopen though if this is still an issue
