### ISSUE TITLE
Value attribute brackets issue

### ISSUE THREAD

**Issue by jjakka** [robdodson/chart-elements#16]
Hi,

When using chart element in my site within a polymer-element and template tag which is being
accessed via app-router with core-animated pages, you get the error seen in the image attached.

The issue is resolved when a space is inserted between the double square brackets in the value like
this:
value="[[1,2,3,4]]"  --->error
value="[ [1,2,3,4] ]"  --->no error

![console-log](https://cloud.githubusercontent.com/assets/5233306/6535155/a3bcbc00-c410-11e4-8166-9731d4af93dd.png)

**Comment by robdodson** [comment]
This looks like a Polymer bug to me. Going to close because soon I'll be porting over to 0.8
