### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by hungerhab** [robdodson/chart-elements#18]
Hi,
I'm trying to use Polymer for my Master Thesis. I would like to know how I can put options to <chart-pie>, because I would like to have a legend and a title for my charts. Can anyone help me? A very small example would help ma a lot!

Thank you!

**Comment by gattasrikanth** [comment]
+1 on options.
Would be very helpful to get started if there is an example.

**Comment by robdodson** [comment]
Options should be  supported in the latest release.
