### ISSUE TITLE
polymer 1.0

### ISSUE THREAD

**Issue by j-mi-jim** [robdodson/chart-elements#20]
is it working with polymer 1.0 ?

**Comment by sandro-k** [comment]
@j-mi-jim  the [0.8](/robdodson/chart-elements/tree/0.8) branch was almost working with 1.0. I forked the repository to [/andro-k/chart-elements](/sandro-k/chart-elements) and used the stat of the 0.8 branch to create a [1.0](/sandro-k/chart-elements/tree/1.0) and made the changes to get it working with polymer 1.0. Please give it a try and give me some feedback.. you can install it with

```
bower install --save sandro-k/chart-elements#1.0
```

**Comment by sandro-k** [comment]
@robdodson how are your plans withe the chart-elements? Would you like to merge my changes into your repository?

**Comment by robdodson** [comment]
@sandro-k yeah if you want to open a PR I could merge it in and make you a maintainer if you'd be interested?

**Comment by sandro-k** [comment]
@robdodson sounds good :+1: Let me play around with the elements a little and test every one. I run into issues some times when resizing the charts at runtime.

**Comment by robdodson** [comment]
Just pushed a new version that's 1.0 compliant
