### ISSUE TITLE
chart-bar does not render unless updateChart() is called after `attached`

### ISSUE THREAD

**Issue by frontrangerider2004** [robdodson/chart-elements#29]
Hey Rob,

Thanks for putting these chart elements together! 

Trying to get a `<chart-bar>` to work and noticed it will not render. The element exists in the DOM but the console prints a canvas undefined error during page load and you get a blank screen.

After page load I can get it to render by manually calling `updateChart()`. This appears to be related to life-cycle timing. I was able to solve both problems by doing two things:

1. checking for `isAttached` within `updateChart()` 

2. calling `updateChart()` within the `attached` callback

See [my Gist of char-bar](https://gist.github.com/frontrangerider2004/cf8171353eca8f4bebaa) for the complete code.

**Comment by robdodson** [comment]
Can you explain a bit more about how you're using it. It renders OK in the
demo so I feel like there must be more going on. Are you using it within
iron-pages or dynamically inserting it?

**Comment by frontrangerider2004** [comment]
Thanks for the quick response! 

Happy to provide more detail. As a pre-cursor to doing anything with other elements I tried putting together a very basic sample. 

1. I created a custom element called `<my-chart>` to hold my data. 

2. I put an instance of `<chart-bar>` inside of that. 

3. I bound the data from `<my-chart>` to `<chart-bar>`

4. I put my element inside my main app.html as the only element.

See this Gist for [my example app](https://gist.github.com/frontrangerider2004/fc68de9a9ed201e1dd57)

Eventually I'd like to use the chart inside a flex layout and have it be responsive...

**Comment by robdodson** [comment]
ok i think i see what may be causing the possible bug... i'll have to work
on this a bit

**Comment by robdodson** [comment]
I just pushed a change to master. Would you mind trying again with that latest version?

**Comment by frontrangerider2004** [comment]
Awesome! No problem. I probably won't get to it until tomorrow or Monday
but it will be first on my list.

**Comment by frontrangerider2004** [comment]
Just tried the update and it works great! Good call on putting it in the data behavior as opposed to where I had it in the chart. Now all the chart elements can inherit it.

Thanks again!

**Comment by robdodson** [comment]
yay! glad that fixed it. let me know if you find anything else. I'm trying to spend more time on these elements now to improve them a bit

**Comment by frontrangerider2004** [comment]
Awesome! I'll be integrating with some other code this week so I'll keep
you posted.
