### ISSUE TITLE
Multiple elements

### ISSUE THREAD

**Issue by SephVelut** [robdodson/chart-elements#30]
Hi, I'm new to Polymer so I'm not sure if this issue is due to my inexperience. I have the exact same project as https://gist.github.com/frontrangerider2004/fc68de9a9ed201e1dd57. The only difference is I have a second element:

`<div class="container">
        <my-chart></my-chart>
        <my-chart></my-chart>
    </div>
`

The canvas for the first element doesn't draw anything. I get a blank. The second `my-chart` renders fine. If I open and close dev tools the first element is suddenly drawn. Am I doing something wrong?

**Comment by SephVelut** [comment]
Pretty sure this is what's causing the behavior

`if (this.chart) {
                        this.chart.destroy();
                    }`

**Comment by robdodson** [comment]
I don't think I'll be able to get to this until after I/O but if you'd like to work on a pull request to patch the issue I'd be happy to review it.

**Comment by SephVelut** [comment]
I'm a little swamped now but I've learned quite a bit about Polymer since opening the issue, so yes to that pull request some time soon.

**Comment by Stormsys** [comment]
This issue doesn't seem to be present with the Chat.js 2 implementation, 

> bower i robdodson/chart-elements#80c50d6 -S

 to test it out.

**Comment by Stormsys** [comment]
closing the issue as discussed above should be resolved in v3.
