### ISSUE TITLE
Update the demo URL to match the new release

### ISSUE THREAD

**Issue by Stormsys** [robdodson/chart-elements#39]
Hey Rob,

Maybe we should update the demo URL (or create a /v3 for version history) to show off the updated elements documentation.

**Comment by robdodson** [comment]
+1 an updated demo would be great

**Comment by Stormsys** [comment]
Question is how? am i able to do it? i noticed its pulling from the gh-pages branch, and you originally used the yo generator

**Comment by robdodson** [comment]
oh I think I can just do it from my end. On a crappy connection at the moment but I'll see if i can push something out today

**Comment by robdodson** [comment]
I pushed a new demo, do you want to give it a look to make sure all your changes made it in?

**Comment by Stormsys** [comment]
Looks good - i noticed that it loses color formatting due to syntax in the docs but its minor - il fix it soon. but other then that all good.

**Comment by robdodson** [comment]
Right on, thanks!
