### ISSUE TITLE
Documentation for chart-doughnut incorrect

### ISSUE THREAD

**Issue by smsukardi** [robdodson/chart-elements#49]
Should be 
`<chart-doughnut data="{{data}}"></chart-doughnut>`
instead of 
`<chart-doughnut values="{{data}}"></chart-doughnut>`
as the latter does not work.

**Comment by robdodson** [comment]
Good catch. Would you be interested in putting together a pull request to
fix the docs?

**Comment by robdodson** [comment]
Ah looks like @pkaske may have already done so 😃
