### ISSUE TITLE
stacked bar

### ISSUE THREAD

**Issue by mahasaez** [robdodson/chart-elements#55]
hello, I've been trying to get stacked bar working but haven't succeded, what I tried is this [question](http://stackoverflow.com/questions/38826017/charts-js-stacked-bar-with-polymers-wrapper-chart-elements) in stackoverflow

**Comment by pkaske** [comment]
You need to use the `options` property of chart-bar. Also, the `data` property expects an object holding the data and labels. I made a working example with stacking for you:

https://jsbin.com/wohivikole/edit?html,output

**Comment by mahasaez** [comment]
Thank you very much ! it's working very well thanks !!

May I just ask if the 100% stacked bar like this one http://www.highcharts.com/demo/column-stacked-percent is implemented because I've seen in a lot of issues here that it's impossible to do.

**Comment by pkaske** [comment]
Seems like this isn't implemented in Chart.js.
Maybe you can manually calculate percentages for your data and use them to achieve some similar? I would recommend to directly address any questions about Chart.js configuration to the Chart.js community on github or stackoverflow.

Anyway, I found this issue:
https://github.com/chartjs/Chart.js/issues/2709

Closing this issue, as your original question is resolved.
