### ISSUE TITLE
animation disable

### ISSUE THREAD

**Issue by ruckc** [robdodson/chart-elements#62]
I've tried everything I can to pass `{animation: false}` in the options attribute, and `{animation: { duration: 0 }}`, but it keeps being animated on open or upon refresh of data.

**Comment by reads** [comment]
Had to google a bit to find precise syntax:

`<chart-bar options='{"animation": false}'></chart-bar>`

src: http://stackoverflow.com/questions/7410348/how-to-set-json-format-to-html5-data-attributes-in-the-jquery

**Comment by ruckc** [comment]
That is very oddly specific in syntax, and it works.  Reversing the quotations around doesn't work and seems counter-intuitive.  I don't understand how either of the below doesn't work.

```
<chart-bar options="{animation: false}"></chart-bar>
<chart-bar options="{'animation': false}"></chart-bar>
```

**Comment by robdodson** [comment]
Reversing the quotes won't work because Polymer runs JSON.parse when you
pass in an object as an attribute. But single quotes are not allowed in JSON
