### ISSUE TITLE
Port to Polymer 2.0?

### ISSUE THREAD

**Issue by johnlim** [robdodson/chart-elements#70]
Hi,

Are there any plans to port chart-elements to Polymer 2.0? If yes, is there any timeline? Thanks :)

Regards,
John

**Comment by pkaske** [comment]
Hi @johnlim,

I just implemented the chart elements with polymer 2.0.
Checkout the polymer-2.0 branch and give it a spin.

Let us know if run into any problems.

**Comment by johnlim** [comment]
Hi Peter,

Awesome! Thanks a lot! Will give it a go and let you know how it goes.

Regards,
John

**Comment by johnlim** [comment]
Hi @pkaske , seems to be working great! Thanks for the port.
