### ISSUE TITLE
Export Image

### ISSUE THREAD

**Issue by Damianruizz** [robdodson/chart-elements#72]
How can I export some graphics as an image?

**Comment by pkaske** [comment]
Each chart element has `chart` property that holds a reference to the chartjs instance.
So, according to http://www.chartjs.org/docs/latest/developers/api.html#tobase64image you can do the following:

```js
const yourChartElement = document.querySelector('chart-pie');
const pngDataUrl = yourChartElement.chart.toBase64Image();
```

**Comment by Damianruizz** [comment]
I work, thank you very much
